const businesses = ref([
    {
       id: 'lemonadeStand',
       rectangleNum: 1,
       name: 'Lemonade stand',
       price: 1,
       timeTaken: 1,
       quantityPurchased: 1,
       profit: 1,
       image: 'lemon.png',
     },
     {
       id: 'newspaperDelivery',
       rectangleNum: 2,
       name: 'Newspaper Deliver',
       price: 30,
       timeTaken: 3,
       quantityPurchased: 0,
       profit: 25,
       image: 'newspaper.png',
     },
     {
       id: 'carWash',
       rectangleNum: 3,
       name: 'Car Wash',
       price: 500,
       timeTaken: 6,
       quantityPurchased: 0,
       profit: 300,
       image: 'car.png',
     },
     pizzaDelivery, {
       id: 'pizzaDelivery',
       rectangleNum: 4,
       name: 'Pizza Delivery',
       price: 3000,
       timeTaken: 12,
       quantityPurchased: 0,
       profit: 2000,
       image: 'pizza.png',
     },
     {
       id: 'donutShop',
       rectangleNum: 5,
       name: 'Donut Shop',
       price: 50000,
       timeTaken: 30,
       quantityPurchased: 0,
       profit: 20000,
       image: 'donut.png',
     },
     {
       id: 'shrimpBoat',
       rectangleNum: 6,
       name: 'Shrimp Boat',
       price: 800000,
       timeTaken: 90,
       quantityPurchased: 0,
       profit: 400000,
       image: 'boat.png',
     },
     {
       id: 'hockeyTeam',
       rectangleNum: 7,
       name: 'Hockey Team',
       price: 6000000,
       timeTaken: 600,
       quantityPurchased: 0,
       profit: 4000000,
       image: 'hockey.png',
     },
     {
       id: 'movieStudio',
       rectangleNum: 8,
       name: 'Movie Studio',
       price: 100000000,
       timeTaken: 3600,
       quantityPurchased: 0,
       profit: 40000000,
       image: 'movie.png',
     },
     {
       id: 'bank',
       rectangleNum: 9,
       name: 'Bank',
       price: 5000000000,
       timeTaken: 36000,
       quantityPurchased: 0,
       profit: 1000000000,
       image: 'bank.png',
     },
     {
       id: 'oilCompany',
       order: 10,
       name: 'Oil Company',
       price: 153434564431,
       timeTaken: 36000,
       quantityPurchased: 0,
       profit: 51434564431,
       image: 'company.png',
     },
   ]);